version: '3'
services:
  app:
    build: .
    volumes:
      - ./app/config:/app/config
    environment:
      - RUN_INDEXER=1
      - RUN_WEB=0
      - NODE_ENV=production
      - DEBUG=0
    ports:
      - 4000:4000
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: indexer
      POSTGRES_USER: indexer
      POSTGRES_DB: indexer
    ports:
      - 5432:5432


