version: '3'
services:
  app:
    build: .
    environment:
      RUN_INDEXER: 1
      RUN_WEB: 0
      NODE_ENV: production
      DEBUG: 1
      CONFIG: >
        {"production":{"username":"indexer","password":"indexer","database":"indexer","host":"db","port":5432,"dialect":"postgres"}}
    ports:
      - 4000:4000
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: indexer
      POSTGRES_USER: indexer
      POSTGRES_DB: indexer
    ports:
      - 5432:5432


